### ISSUE TITLE
API returns incorrect data

### ISSUE THREAD

**Issue by piyasil** [max180643/thai-oil-api#11]
ตั้งแต่วันที่ 3 พค. data มันส่งมาผิด key น่าจะสลับกัน ไม่ทราบว่าแก้ให้ได้ไหมครับ ?

![Screenshot 2567-05-16 at 16 08 17](https://github.com/max180643/thai-oil-api/assets/13187366/890d1b06-a02c-4c62-af8d-910bd73a0872)

**Comment by max180643** [comment]
Fixed with commit https://github.com/max180643/thai-oil-api/commit/6b22f38f4ec830d8b5df2d0a800d01fcb4d6a298
 
 **Remove**
- ptt : diesel_b7, diesel_b20
- bcp : diesel_b7, diesel_b20
- shell : diesel_b7
- caltex : diesel_b7, diesel_b20
- irpc : diesel_b7
- pt : diesel_b7
- susco : diesel_b7
- pure : diesel_b7
- susco_dealers : diesel_b7
